name: hoteldineflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1  # Updated to match firebase_auth
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  appwrite: ^13.1.1
  uuid: ^3.0.7
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
